services:
  backend:
    build: ./Backend
    container_name: drive_backend
    restart: always
    volumes:
      - ./Backend:/app
      - ./data/storage:/app/storage
    environment:
      - MONGO_URI=mongodb://mongodb:27017/drive
    ports:
      - "9000:8000"
    depends_on:
      - mongodb
    networks:
      - drive_network

  frontend:
    build: ./Frontend
    container_name: drive_frontend
    restart: always
    ports:
      - "9001:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:9000
    networks:
      - drive_network

  mongodb:
    image: mongo:6.0
    container_name: drive_mongodb
    restart: always
    ports:
      - "9017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - drive_network

networks:
  drive_network:
    driver: bridge
